repos:
- repo: local
  hooks:
      - id: format
        name: format
        types_or: [python, jupyter]
        entry: uv run ruff format
        language: system
        always_run: false

- repo: local
  hooks:
      - id: lint
        name: lint
        types_or: [python, jupyter]
        entry: uv run ruff check --fix
        language: system
        always_run: false

- repo: local
  hooks:
      - id: check-types
        name: check types
        types_or: [python, jupyter]
        entry: uv run mypy .
        language: system
        always_run: false
        pass_filenames: false
