name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: ${{ vars.UV_VERSION || '0.6.9' }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Initialize venv
        run: uv venv

      - name: Install pre-commit
        run: uv pip install pre-commit ruff mypy

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run ruff
        run: uv run ruff check .

      - name: Run mypy
        run: uv run mypy .
